# spring.application.name=sistema-vendas

# spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_vendas
# spring.datasource.username=usuario
# spring.datasource.password=senha123

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:postgresql://dpg-dauoov0jo6nc73e0lej0-a.virginia-postgres.render.com:5432/sistema_vendas_db_lyb5
spring.datasource.username=sistema_vendas_db_lyb5_user
spring.datasource.password=zLD5fNxP4T7Y4u12LZXyzUmX0SyI1MSO
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}